spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${RENTAL_DB_HOST:127.0.0.1}:${RENTAL_DB_PORT:3306}/${RENTAL_DB_NAME:zza}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8'
    username: ${RENTAL_DB_USERNAME:root}
    password: ${RENTAL_DB_PASSWORD}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1
  data:
    redis:
      host: ${RENTAL_REDIS_HOST:127.0.0.1}
      port: ${RENTAL_REDIS_PORT:6379}
      database: ${RENTAL_REDIS_DATABASE:0}
      password: ${RENTAL_REDIS_PASSWORD}
      timeout: 5s
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER}
